export { default as Hero } from './Hero'
export { default as PainPoints } from './PainPoints'
export { default as SolutionBridge } from './SolutionBridge'
export { default as Features } from './Features'
export { default as SocialProof } from './SocialProof'
export { default as Pricing } from './Pricing'
export { default as FAQ } from './FAQ'
export { default as CTAFinal } from './CTAFinal'
